version: '3.8'

services:
  # PostgreSQL Database for development/testing
  postgres:
    image: postgres:15-alpine
    container_name: movie-explorer-postgres
    environment:
      POSTGRES_DB: movie_explorer
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/data:/docker-entrypoint-initdb.d/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_explorer"]
      interval: 30s
      timeout: 10s
      retries: 5

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: movie-explorer-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@movieexplorer.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: movie-explorer-network
